### PR TITLE
fix(tracker): add the option to run tracking outside of angular zone

### LINKED ISSUE #60: Application freezes sometimes
Bonjour Emmanuel,

Dans le cadre d'un projet, j'ai dû intégrer Matomo afin de faire du tracking basique.
J'utilise la version 3.2.0 du ngx-matomo/router (donc la dernière version).

Depuis la mise en place du module, sur certaines actions, j'ai un freeze complet de mon application. Je dois fermer l'onglet et en ouvrir un nouveau. Ce problème est reproduit sur plusieurs navigateurs (FF, Chrome) et par plusieurs personnes sur plusieurs environnements.

C'est un problème qui arrive pendant une navigation (changement de page), à chaque fois depuis les mêmes pages, vers n'importe laquelle.

Lorsque je passe le paramètre "disabled" à true dans le MatomoConfiguration, je n'ai plus de problème (mais plus de tracking non plus). Dès que je le réactive, le problème apparait.

Avez-vous des retours quant à ce problème?

Merci d'avance

### PR DESCRIPTION
**Pull request by Arrakis-Lux**
Fixes #60

- Adds an option in configs to run the tracker outside of angular ngZone

Tests are broken though I have very little experience with those and the fix did not appeared to be obvious.

### CODE REVIEW

**Comment by EmmanuelRoux** [comment]
Thanks for the PR @Arrakis-Lux 

You can add some tests like that:

<details><summary>Git Patch</summary>

```diff
Index: projects/tracker/src/lib/matomo-tracker.service.spec.ts
<+>UTF-8
===================================================================
diff --git a/projects/tracker/src/lib/matomo-tracker.service.spec.ts b/projects/tracker/src/lib/matomo-tracker.service.spec.ts
--- a/projects/tracker/src/lib/matomo-tracker.service.spec.ts	(revision 736dd3637ced5f88bd2451d648dee85ed3b18e45)
+++ b/projects/tracker/src/lib/matomo-tracker.service.spec.ts	(date 1669319256568)
@@ -1,3 +1,4 @@
+import { NgZone } from '@angular/core';
 import { InternalMatomoConfiguration } from './configuration';
 import { MatomoHolder } from './holder';
 import {
@@ -15,8 +16,16 @@
 const PLATFORM_SERVER_ID = 'server';
 
 describe('MatomoTracker', () => {
-  function createTracker(disabled = false, platform: Object = PLATFORM_BROWSER_ID): MatomoTracker {
-    return createMatomoTracker({ disabled } as InternalMatomoConfiguration, platform);
+  function createMockZone(): jasmine.SpyObj<NgZone> {
+    return jasmine.createSpyObj<NgZone>(['runOutsideAngular']);
+  }
+
+  function createTracker(
+    config: Partial<InternalMatomoConfiguration> = { disabled: false },
+    platform: Object = PLATFORM_BROWSER_ID,
+    ngZone: NgZone = createMockZone()
+  ): MatomoTracker {
+    return createMatomoTracker(config as InternalMatomoConfiguration, platform, ngZone);
   }
 
   beforeEach(() => {
@@ -632,7 +641,7 @@
 
   it('should ignore calls when disabled', () => {
     // Given
-    const tracker = createTracker(true);
+    const tracker = createTracker({ disabled: true });
     (window as any)._paq = undefined;
 
     // Then
@@ -642,7 +651,7 @@
 
   it('should reject all promises when disabled', done => {
     // Given
-    const tracker = createTracker(true);
+    const tracker = createTracker({ disabled: true });
 
     // Then
     tracker
@@ -656,7 +665,7 @@
 
   it('should ignore calls when platform is not browser', () => {
     // Given
-    const tracker = createTracker(false, PLATFORM_SERVER_ID);
+    const tracker = createTracker({ disabled: false }, PLATFORM_SERVER_ID);
     (window as any)._paq = undefined;
 
     // Then
@@ -666,7 +675,7 @@
 
   it('should reject all promises when platform is not browser', done => {
     // Given
-    const tracker = createTracker(false, PLATFORM_SERVER_ID);
+    const tracker = createTracker({ disabled: false }, PLATFORM_SERVER_ID);
 
     // Then
     tracker
@@ -677,4 +686,23 @@
         done();
       });
   });
+
+  it('should run commands outside Angular Zone', () => {
+    // Given
+    const zone = createMockZone();
+    const tracker = createTracker({ runOutsideAngularZone: true }, PLATFORM_BROWSER_ID, zone);
+    let runOutside = false;
+
+    zone.runOutsideAngular.and.callFake(fn => {
+      runOutside = true;
+      return fn();
+    });
+
+    // When
+    tracker.ping();
+
+    // Then
+    expect(runOutside).toBeTrue();
+    expect(window._paq).toEqual([['ping']]);
+  });
 });
```

</details>

**Comment by Arrakis-Lux** [comment]
Hey there ! 

Hope you had a nice evening ! 

Just added the suggered tests (thanks for that :p I really need to work on this aspect ^-^)

Also updated the configuration documentation. I am not sure about the "Available in manual mode" part though.

**Comment by EmmanuelRoux** [comment]
@Arrakis-Lux Thank you, looks good to me!

Maybe we can do some optimization in the future, but we can keep it as-is for a first opt-in fix.
This fix might become a default in a future version of the lib. For that reason, please let us know any feedback in this PR or in a new issue!

**Pull request merged**
